### ISSUE TITLE
Question: How to register a new user and start writing on mablo.meteor.com?

### ISSUE THREAD

**Issue by kevingzhang** [yejodido/mablo#1]

**Comment by kevingzhang** [comment]
Sorry, I just realized i can go /admin.

**Comment by nogtini** [comment]
To get started, you'll want to start your own Meteor project ($ meteor create kevingzhang-blog) and use the cloned files provided in the repo to host your own instance of Mablo! Make sure you install the dependencies listed under "Packages Used", and then you're free to run it on localhost or publish it using the method of your choice. Thank you for using!
